### PR TITLE
Correctly handle on_reload, on_detach, refactor indexing functions

### LINKED ISSUE #14: Error about invalid buffer id
I sometimes get this error out of the blue. And I can't make the error go away because it keeps popping up after I close it. I don't know how to reproduce it yet.

image

### PR DESCRIPTION
**Pull request by dmitmel**
Ref: #12 \
Depends on: #18

Addresses point 6 of my original PR. Also refactored functions which perform indexing.

Fixes #14.

### CODE REVIEW

**Comment by gegoune** [comment]
Apologies for not contributing to discussion and adding any value, just wanted to say big thanks to you @dmitmel for all your contributions. You guys rock!

**Comment by dmitmel** [comment]
Rebased

**Comment by hrsh7th** [comment]
I have one question. Do you think the first asynchronous indexing is useful or not?

I have same opinion that the first async indexing can't be complete correctly (because the buffer can be changed by the user during it).

**Comment by hrsh7th** [comment]
@dmitmel has higher skills than me. You are great!

**Comment by hrsh7th** [comment]
@dmitmel I'm sorry. My English may not be understood.

I have a question.
Do you think the first asynchronous indexing makes sense? If synchronization is enough for the first indexing, I think it's better to remove the asynchronous logic.

First, it indexes everything synchronously, and from there it incrementally processes via events.

_google translated_

**Comment by dmitmel** [comment]
(Please wait, I'll respond later, I haven't forgotten about this ticket)

**Comment by dmitmel** [comment]
> I have one question. Do you think the first asynchronous indexing is useful or not?

Yes. I think it is. I see two purposes in it:

1. I consider the buffer source "dumb completion" as opposed to Language Servers which provide "smart completion". If I start editing a new file, the buffer source will start indexing it, but with async indexing I will have much less lag due to blocking, I'll most likely receive completions from the Language Server right away (since they typically index the whole project beforehand) and won't be particularly sad that some random word at the end of the file couldn't be completed on the first keystroke (but since isIncomplete is set, I will see it after typing for a bit).
2. If I accidentally open a big file and start editing it, the editor won't freeze, but I will be able to see high CPU usage and close the editor. Here async indexeing is a fail-safe mechanism for big files.

Though I do think that the default interval can be reduced. On my machine each 1000 lines take about 10 ms to index, so I think it's fair to set the interval to 40 ms or something like that, not 200. 10ms per chunk leaves room for nearly 60 FPS rendering, which I think is good enough.

>  Do you think the first asynchronous indexing makes sense? If synchronization is enough for the first indexing, I think it's better to remove the asynchronous logic.

> I have same opinion that the first async indexing can't be completed correctly (because the buffer can be changed by the user during it).

I have an idea how to fix this. I'll implement it tomorrow in #23 which I have marked as a draft. But let's discuss this in that PR and keep merging the other PRs. Could you please take a look at #25? I'd prefer to get your comments and merge that one first and rebase my other stuff on top of it.

**Comment by hrsh7th** [comment]
OK. Thank you for response.

I'm trying to realize the real asynchronous operation in neovim's Lua with regex support.
https://github.com/hrsh7th/nvim-lua-rpc-example-with-headless

it might be promising to use in this plugin.

File: lua/cmp_buffer/buffer.lua [hunk 1]
```diff
@@ -20,74 +23,127 @@ function buffer.new(bufnr, length, pattern)
...
+    local chunk_start = range_start
+    while chunk_start < range_end do
+      local chunk_end = math.min(chunk_start + chunk_size, range_end)
+      local chunk_lines = vim.api.nvim_buf_get_lines(self.bufnr, chunk_start, chunk_end, true)
+      for i, line in ipairs(chunk_lines) do
+        self:index_line(chunk_start + i, line)
+      end
+      chunk_start = chunk_end
+    end
+  end)
```
Comment (hrsh7th) [inline lua/cmp_buffer/buffer.lua:79]: I think this loop is not needed because all operation done in synchronous context.
we can use `nvim_buf_get_lines(self.bufnr, range_start, range_end)`

Comment (dmitmel) [reply lua/cmp_buffer/buffer.lua:79]: Oh right, I was getting ahead of myself. This is the memory usage optimization that has to go into #23.

Comment (hrsh7th) [reply lua/cmp_buffer/buffer.lua:79]: Oh. I see https://github.com/hrsh7th/cmp-buffer/pull/23/files#diff-c85bd8eb792c08892360d3ae503c5e744f5206e15fa468dc3ed11ecdd9b3b48bR107

Comment (dmitmel) [reply lua/cmp_buffer/buffer.lua:79]: Give me a second please, I will figure out how I made the same changes twice

Comment (dmitmel) [reply lua/cmp_buffer/buffer.lua:79]: Oh, nevermind. Anyway, I'll move this change (the inner loop) to #23.

File: lua/cmp_buffer/buffer.lua [hunk 2]
```diff
@@ -20,74 +23,119 @@ function buffer.new(bufnr, length, pattern)
...
+function buffer.index_range_async(self, range_start, range_end, chunk_size)
+  if chunk_size < 1 then
+    chunk_size = range_end - range_start
+  end
+  local chunk_start = range_start
+
+  local lines = vim.api.nvim_buf_get_lines(self.bufnr, range_start, range_end, true)
+  -- This flag prevents vim.schedule() callbacks from piling up in the queue
+  -- when the indexing interval is very short.
+  local scheduled = false
```
Comment (dmitmel) [inline lua/cmp_buffer/buffer.lua:83]: This should also be part of #23
